package ffi

import (
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type BindingManifest struct {
	Module    string                    `yaml:"module"`
	Library   string                    `yaml:"library"`
	Doc       string                    `yaml:"doc"`
	Structs   map[string]BindingStruct  `yaml:"structs"`
	Functions []BindingFunction         `yaml:"functions"`
	Constants []BindingConstant         `yaml:"constants"`
}

type BindingStruct struct {
	Doc    string         `yaml:"doc"`
	Fields []BindingField `yaml:"fields"`
}

type BindingField struct {
	Name string `yaml:"name"`
	Type string `yaml:"type"`
}

type BindingFunction struct {
	Name    string   `yaml:"name"`
	Doc     string   `yaml:"doc"`
	Args    []string `yaml:"args"`
	Returns string   `yaml:"returns"`
}

type BindingConstant struct {
	Name  string `yaml:"name"`
	Value string `yaml:"value"`
	Doc   string `yaml:"doc"`
}

func ParseBindingManifest(data []byte) (*BindingManifest, error) {
	var m BindingManifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse binding manifest: %w", err)
	}
	if m.Module == "" {
		return nil, fmt.Errorf("binding manifest: module is required")
	}
	if m.Library == "" {
		return nil, fmt.Errorf("binding manifest: library is required")
	}
	return &m, nil
}

func GenerateBindings(m *BindingManifest) (string, error) {
	if err := validateManifest(m); err != nil {
		return "", err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "module %s;\n\n", m.Module)
	fmt.Fprintf(&b, "/* Generated by `geblang bind`. Do not edit by hand. */\n")
	if m.Doc != "" {
		fmt.Fprintf(&b, "\n/**\n")
		for _, line := range strings.Split(strings.TrimSpace(m.Doc), "\n") {
			fmt.Fprintf(&b, " * %s\n", line)
		}
		fmt.Fprintf(&b, " */\n")
	}
	fmt.Fprintf(&b, "\nimport ffi;\n\n")
	fmt.Fprintf(&b, "let _lib = ffi.dlopen(%q);\n\n", m.Library)

	for _, c := range m.Constants {
		if c.Doc != "" {
			fmt.Fprintf(&b, "/** %s */\n", strings.TrimSpace(c.Doc))
		}
		fmt.Fprintf(&b, "export const int %s = %s;\n", c.Name, c.Value)
	}
	if len(m.Constants) > 0 {
		fmt.Fprintln(&b)
	}

	structNames := sortedStructNames(m.Structs)
	for _, name := range structNames {
		s := m.Structs[name]
		if s.Doc != "" {
			fmt.Fprintf(&b, "/** %s */\n", strings.TrimSpace(s.Doc))
		}
		fmt.Fprintf(&b, "export let %s = ffi.StructOf([\n", name)
		for _, f := range s.Fields {
			fmt.Fprintf(&b, "    [%q, %s],\n", f.Name, ffiTypeRef(f.Type))
		}
		fmt.Fprintln(&b, "]);")
		fmt.Fprintln(&b)
	}

	for _, f := range m.Functions {
		argTypes := make([]string, len(f.Args))
		for i, a := range f.Args {
			argTypes[i] = ffiTypeRef(a)
		}
		retTypeRef := ffiTypeRef(f.Returns)
		fmt.Fprintf(&b, "let _%s = _lib.symbol(%q, [%s], %s);\n",
			f.Name, f.Name, strings.Join(argTypes, ", "), retTypeRef)
		if f.Doc != "" {
			fmt.Fprintf(&b, "/** %s */\n", strings.TrimSpace(f.Doc))
		}
		params := make([]string, len(f.Args))
		paramNames := make([]string, len(f.Args))
		for i, a := range f.Args {
			params[i] = fmt.Sprintf("%s a%d", geblangParamType(a), i)
			paramNames[i] = fmt.Sprintf("a%d", i)
		}
		returnGT := geblangReturnType(f.Returns)
		if returnGT == "void" {
			fmt.Fprintf(&b, "export func %s(%s): void {\n",
				f.Name, strings.Join(params, ", "))
			fmt.Fprintf(&b, "    _%s(%s);\n", f.Name, strings.Join(paramNames, ", "))
			fmt.Fprintf(&b, "}\n\n")
		} else {
			fmt.Fprintf(&b, "export func %s(%s): %s {\n",
				f.Name, strings.Join(params, ", "), returnGT)
			fmt.Fprintf(&b, "    return _%s(%s) as %s;\n",
				f.Name, strings.Join(paramNames, ", "), returnGT)
			fmt.Fprintf(&b, "}\n\n")
		}
	}
	return b.String(), nil
}

func validateManifest(m *BindingManifest) error {
	for i, f := range m.Functions {
		if f.Name == "" {
			return fmt.Errorf("function %d: name is required", i)
		}
		if f.Returns == "" {
			return fmt.Errorf("function %s: returns is required (use VOID for no return)", f.Name)
		}
		if _, err := bindingType(f.Returns); err != nil {
			return fmt.Errorf("function %s: %w", f.Name, err)
		}
		for j, a := range f.Args {
			if _, err := bindingType(a); err != nil {
				return fmt.Errorf("function %s arg %d: %w", f.Name, j, err)
			}
		}
	}
	for name, s := range m.Structs {
		if len(s.Fields) == 0 {
			return fmt.Errorf("struct %s: at least one field required", name)
		}
		for i, f := range s.Fields {
			if f.Name == "" {
				return fmt.Errorf("struct %s field %d: name is required", name, i)
			}
			t, err := bindingType(f.Type)
			if err != nil {
				return fmt.Errorf("struct %s field %s: %w", name, f.Name, err)
			}
			if _, err := typeSize(t); err != nil {
				return fmt.Errorf("struct %s field %s: %w", name, f.Name, err)
			}
		}
	}
	return nil
}

func bindingType(name string) (Type, error) {
	upper := strings.ToUpper(strings.TrimSpace(name))
	switch upper {
	case "VOID":
		return Void, nil
	case "INT8":
		return Int8, nil
	case "INT16":
		return Int16, nil
	case "INT32":
		return Int32, nil
	case "INT64":
		return Int64, nil
	case "UINT8":
		return Uint8, nil
	case "UINT16":
		return Uint16, nil
	case "UINT32":
		return Uint32, nil
	case "UINT64":
		return Uint64, nil
	case "FLOAT":
		return Float32, nil
	case "DOUBLE":
		return Float64, nil
	case "PTR":
		return Ptr, nil
	case "CSTRING":
		return CString, nil
	case "BYTES":
		return Bytes, nil
	}
	return 0, fmt.Errorf("unknown FFI type %q", name)
}

func ffiTypeRef(name string) string {
	return "ffi." + strings.ToUpper(strings.TrimSpace(name))
}

func geblangParamType(ffiName string) string {
	t, _ := bindingType(ffiName)
	switch t {
	case Float32, Float64:
		return "decimal"
	case CString:
		return "string"
	case Bytes:
		return "bytes"
	}
	return "int"
}

func geblangReturnType(ffiName string) string {
	t, _ := bindingType(ffiName)
	switch t {
	case Void:
		return "void"
	case Float32, Float64:
		return "decimal"
	case CString:
		return "string"
	case Bytes:
		return "bytes"
	}
	return "int"
}

func sortedStructNames(m map[string]BindingStruct) []string {
	names := make([]string, 0, len(m))
	for n := range m {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}
