package evaluator

import (
	"fmt"
	"io"

	"geblang/internal/ast"
	"geblang/internal/runtime"

	_ "github.com/go-sql-driver/mysql"
	_ "github.com/jackc/pgx/v5/stdlib"
	_ "modernc.org/sqlite"
)

func (e *Evaluator) builtinModules() map[string]map[string]builtinFunc {
	return map[string]map[string]builtinFunc{
		"io": {
			"print": func(call *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				text, err := e.singlePrintableValue(call, args)
				if err != nil {
					return nil, err
				}
				_, err = fmt.Fprint(e.stdout, text)
				return runtime.Null{}, err
			},
			"println": func(call *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				text, err := e.singlePrintableValue(call, args)
				if err != nil {
					return nil, err
				}
				_, err = fmt.Fprintln(e.stdout, text)
				return runtime.Null{}, err
			},
			"readText":       ioReadText,
			"writeText":      ioWriteText,
			"appendText":     ioAppendText,
			"readBytes":      e.ioReadBytes,
			"writeBytes":     e.ioWriteBytes,
			"appendBytes":    ioAppendBytes,
			"exists":         ioExists,
			"tempFile":       ioTempFile,
			"tempDir":        ioTempDir,
			"open":           e.ioOpen,
			"memory":         e.ioMemory,
			"stdin":          e.ioStdin,
			"stdout":         e.ioStdout,
			"stderr":         e.ioStderr,
			"read":           e.ioRead,
			"readAll":        e.ioReadAll,
			"write":          e.ioWrite,
			"writeln":        e.ioWriteln,
			"flush":          e.ioFlush,
			"sync":           e.ioSync,
			"dataSync":       e.ioDataSync,
			"lock":           e.ioLock,
			"tryLock":        e.ioTryLock,
			"unlock":         e.ioUnlock,
			"close":          e.ioClose,
			"readCSV":        ioReadCSV,
			"writeCSV":       ioWriteCSV,
			"stat":           ioStat,
			"lstat":          ioLstat,
			"chmod":          ioChmod,
			"chown":          ioChown,
			"mkdir":          ioMkdir,
			"remove":         ioRemove,
			"rename":         ioRename,
			"copy":           ioCopy,
			"copyTree":       ioCopyTree,
			"move":           ioMove,
			"touch":          ioTouch,
			"writeTextAtomic": ioWriteTextAtomic,
			"symlink":        ioSymlink,
			"readLink":       ioReadLink,
			"listDir":        ioListDir,
			"scanDir":        ioScanDir,
			"walkDir":        ioWalkDir,
			"seek":           e.ioSeek,
			"tell":           e.ioTell,
			"truncate":       e.ioTruncate,
			"atEnd":          e.ioAtEnd,
			"buffer":         e.ioBuffer,
			"bufferToString": e.ioBufferToString,
			"bufferReset":    e.ioBufferReset,
			"toString":       e.ioToString,
			"captureStdout":  e.ioCaptureStdout,
			"captureStderr":  e.ioCaptureStderr,
			"redirectStdout": e.ioRedirectStdout,
			"redirectStderr": e.ioRedirectStderr,
			"redirectStdin":  e.ioRedirectStdin,
			"stdoutWrite": func(call *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				text, err := singleStringValue(call, args)
				if err != nil {
					return nil, err
				}
				_, err = io.WriteString(e.stdout, text)
				return runtime.Null{}, err
			},
			"stderrWrite": func(call *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				text, err := singleStringValue(call, args)
				if err != nil {
					return nil, err
				}
				_, err = io.WriteString(e.stderr, text)
				return runtime.Null{}, err
			},
			"stderrPrintln": func(call *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				text, err := e.singlePrintableValue(call, args)
				if err != nil {
					return nil, err
				}
				_, err = fmt.Fprintln(e.stderr, text)
				return runtime.Null{}, err
			},
			"stdinReadAll":  e.ioStdinReadAll,
			"stdinReadLine": e.ioStdinReadLine,
			"readLine":      e.ioReadLine,
			"readLines":     e.ioReadLines,
			"withStdin":     e.ioWithStdin,
		},
		"sys": {
			"exit": func(call *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				code, err := singleIntValue(call, args)
				if err != nil {
					return nil, err
				}
				return exitValue{code: int(code)}, nil
			},
			"cwd":                sysCwd,
			"getenv":             sysGetenv,
			"bundleDir":          sysBundleDir,
			"args":               e.sysArgs,
			"run":                sysRun,
			"runWithOptions":     sysRunWithOptions,
			"shell":              sysShell,
			"start":              e.sysStart,
			"startWithOptions":   e.sysStartWithOptions,
			"processWrite":       e.sysProcessWrite,
			"processCloseStdin":  e.sysProcessCloseStdin,
			"processReadStdout":  e.sysProcessReadStdout,
			"processReadStderr":  e.sysProcessReadStderr,
			"processReadStdoutN": e.sysProcessReadStdoutN,
			"processReadStderrN": e.sysProcessReadStderrN,
			"processWait":        e.sysProcessWait,
			"processKill":        e.sysProcessKill,
			"processSignal":      e.sysProcessSignal,
			"processPid":         e.sysProcessPid,
			"setenv":             sysSetenv,
			"sleep":              sysSleep,
			"onSignal":           e.sysOnSignal,
			"clearSignal":        e.sysClearSignal,
			"raise":              e.sysRaise,
			"hostname":           e.registryBuiltin("sys", "hostname"),
			"pid":                e.registryBuiltin("sys", "pid"),
			"goroutineId":        e.registryBuiltin("sys", "goroutineId"),
			"platform":           e.registryBuiltin("sys", "platform"),
			"arch":               e.registryBuiltin("sys", "arch"),
			"tmpdir":             e.registryBuiltin("sys", "tmpdir"),
			"homedir":            e.registryBuiltin("sys", "homedir"),
			"username":           e.registryBuiltin("sys", "username"),
			"environ":            e.registryBuiltin("sys", "environ"),
			"osVersion":          e.registryBuiltin("sys", "osVersion"),
		},
		"process": {
			"run": func(call *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				spec, err := processSpecFromCombinedArgs(call, args)
				if err != nil {
					return nil, err
				}
				raw, err := runProcessSpec(spec)
				if err != nil {
					return nil, err
				}
				return e.newProcessResult(raw)
			},
			"runWithOptions": func(call *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				spec, err := processSpecFromOptions(call, args)
				if err != nil {
					return nil, err
				}
				raw, err := runProcessSpec(spec)
				if err != nil {
					return nil, err
				}
				return e.newProcessResult(raw)
			},
			"shell": func(call *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				if len(args) != 1 {
					return nil, fmt.Errorf("%s expects 1 argument", call.Callee.String())
				}
				cmd, ok := args[0].(runtime.String)
				if !ok {
					return nil, fmt.Errorf("%s argument must be string", call.Callee.String())
				}
				raw, err := runProcessSpec(processSpec{command: "sh", args: []string{"-c", cmd.Value}})
				if err != nil {
					return nil, err
				}
				return e.newProcessResult(raw)
			},
			"start": func(call *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				spec, err := processSpecFromCombinedArgs(call, args)
				if err != nil {
					return nil, err
				}
				handle, err := e.startProcessSpec(spec)
				if err != nil {
					return nil, err
				}
				return &runtime.Instance{Class: e.processClass, Fields: map[string]runtime.Value{"handle": handle}}, nil
			},
			"startWithOptions": func(call *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				spec, err := processSpecFromOptions(call, args)
				if err != nil {
					return nil, err
				}
				handle, err := e.startProcessSpec(spec)
				if err != nil {
					return nil, err
				}
				return &runtime.Instance{Class: e.processClass, Fields: map[string]runtime.Value{"handle": handle}}, nil
			},
			"pid":     e.registryBuiltin("process", "pid"),
			"ppid":    e.registryBuiltin("process", "ppid"),
			"uid":     e.registryBuiltin("process", "uid"),
			"gid":     e.registryBuiltin("process", "gid"),
			"euid":    e.registryBuiltin("process", "euid"),
			"egid":    e.registryBuiltin("process", "egid"),
			"groups":  e.registryBuiltin("process", "groups"),
			"list":    e.registryBuiltin("process", "list"),
			"info":    e.registryBuiltin("process", "info"),
			"exists":  e.registryBuiltin("process", "exists"),
			"setuid":  e.registryBuiltin("process", "setuid"),
			"setgid":  e.registryBuiltin("process", "setgid"),
			"kill":    e.registryBuiltin("process", "kill"),
			"signal":  e.registryBuiltin("process", "signal"),
		},
		"procnative": {
			"spawn":  e.procSpawn,
			"wait":   e.procWait,
			"kill":   e.procKill,
			"signal": e.procSignal,
			"pid":    e.procPid,
		},
		"sshnative": {
			"connect":       e.sshConnect,
			"exec":          e.sshExec,
			"spawn":         e.sshSpawn,
			"sessionWait":   e.sshSessionWait,
			"sessionKill":   e.sshSessionKill,
			"upload":        e.sshUpload,
			"download":      e.sshDownload,
			"sftpList":      e.sshSftpList,
			"sftpRemove":    e.sshSftpRemove,
			"sftpMkdir":     e.sshSftpMkdir,
			"sftpOpen":      e.sshSftpOpen,
			"forwardLocal":  e.sshForwardLocal,
			"forwardRemote": e.sshForwardRemote,
			"tunnelClose":   e.sshTunnelClose,
			"close":         e.sshClose,
		},
		"async": {
			"run":     e.asyncRun,
			"sleep":   asyncSleep,
			"await":   asyncAwait,
			"done":    asyncDone,
			"all":     asyncAll,
			"race":    asyncRace,
			"timeout": asyncTimeout,
			"cancel":  asyncCancel,
			"token":   asyncToken,
		},
		"amqp": {
			"dial":            e.amqpDial,
			"channel":         e.amqpChannel,
			"declareQueue":    e.amqpDeclareQueue,
			"declareExchange": e.amqpDeclareExchange,
			"queueBind":       e.amqpQueueBind,
			"publish":         e.amqpPublish,
			"get":             e.amqpGet,
			"ack":             e.amqpAck,
			"close":           e.amqpClose,
		},
		"kafka": {
			"writer": e.kafkaWriter,
			"write":  e.kafkaWrite,
			"reader": e.kafkaReader,
			"read":   e.kafkaRead,
			"commit": e.kafkaCommit,
			"close":  e.kafkaClose,
		},
		"json": {
			"parse":            e.registryBuiltin("json", "parse"),
			"parseAs":          e.registryBuiltin("json", "parseAs"),
			"stringify":        e.registryBuiltin("json", "stringify"),
			"validate":         e.registryBuiltin("json", "validate"),
			"tryParse":         e.registryBuiltin("json", "tryParse"),
			"validateDetailed": e.registryBuiltin("json", "validateDetailed"),
			"reader":           e.jsonReader,
			"stream":           e.jsonStream,
		},
		"xml": {
			"parse":            e.registryBuiltin("xml", "parse"),
			"parseAs":          e.registryBuiltin("xml", "parseAs"),
			"tryParse":         e.registryBuiltin("xml", "tryParse"),
			"stringify":        e.registryBuiltin("xml", "stringify"),
			"validate":         e.registryBuiltin("xml", "validate"),
			"validateDetailed": e.registryBuiltin("xml", "validateDetailed"),
			"reader":           e.xmlReader,
			"stream":           e.xmlStream,
		},
		"toml": {
			"parse":            e.registryBuiltin("toml", "parse"),
			"parseAs":          e.registryBuiltin("toml", "parseAs"),
			"tryParse":         e.registryBuiltin("toml", "tryParse"),
			"stringify":        e.registryBuiltin("toml", "stringify"),
			"validate":         e.registryBuiltin("toml", "validate"),
			"validateDetailed": e.registryBuiltin("toml", "validateDetailed"),
		},
		"yaml": {
			"parse":            e.registryBuiltin("yaml", "parse"),
			"parseAs":          e.registryBuiltin("yaml", "parseAs"),
			"tryParse":         e.registryBuiltin("yaml", "tryParse"),
			"stringify":        e.registryBuiltin("yaml", "stringify"),
			"validate":         e.registryBuiltin("yaml", "validate"),
			"validateDetailed": e.registryBuiltin("yaml", "validateDetailed"),
			"reader":           e.yamlReader,
			"stream":           e.yamlStream,
		},
		"csv": {
			"reader":    e.csvReader,
			"stream":    e.csvStream,
			"parse":     e.registryBuiltin("csv", "parse"),
			"parseDict": e.registryBuiltin("csv", "parseDict"),
			"stringify": e.registryBuiltin("csv", "stringify"),
		},
		"bytes": {
			"fromString":    e.registryBuiltin("bytes", "fromString"),
			"fromList":      e.registryBuiltin("bytes", "fromList"),
			"toString":      e.registryBuiltin("bytes", "toString"),
			"fromHex":       e.registryBuiltin("bytes", "fromHex"),
			"toHex":         e.registryBuiltin("bytes", "toHex"),
			"fromBase64":    e.registryBuiltin("bytes", "fromBase64"),
			"toBase64":      e.registryBuiltin("bytes", "toBase64"),
			"fromBase64Url": e.registryBuiltin("bytes", "fromBase64Url"),
			"toBase64Url":   e.registryBuiltin("bytes", "toBase64Url"),
			"concat":        e.registryBuiltin("bytes", "concat"),
		},
		"string": {
			"fromCodePoint":  e.registryBuiltin("string", "fromCodePoint"),
			"fromCodePoints": e.registryBuiltin("string", "fromCodePoints"),
			"compare":        e.registryBuiltin("string", "compare"),
			"equalsFold":     e.registryBuiltin("string", "equalsFold"),
		},
		"collections": {
			"length":          collectionsLength,
			"isEmpty":         collectionsIsEmpty,
			"contains":        collectionsContains,
			"reverse":         collectionsReverse,
			"sort":            collectionsSort,
			"join":            collectionsJoin,
			"range":           collectionsRange,
			"take":            collectionsTake,
			"lazyMap":         e.collectionsLazyMap,
			"lazyFilter":      e.collectionsLazyFilter,
			"map":             e.collectionsMethod("map", 2),
			"filter":          e.collectionsMethod("filter", 2),
			"reduce":          e.collectionsMethod("reduce", 3),
			"find":            e.collectionsMethod("find", 2),
			"any":             e.collectionsMethod("any", 2),
			"all":             e.collectionsMethod("all", 2),
			"flatten":         e.collectionsMethod("flatten", 1),
			"unique":          e.collectionsMethod("unique", 1),
			"zip":             e.collectionsMethod("zip", 2),
			"sorted":          e.collectionsMethod("sorted", -1),
			"groupBy":         e.collectionsMethod("groupBy", 2),
			"chunk":           e.collectionsMethod("chunk", 2),
			"partition":       e.collectionsMethod("partition", 2),
			"findLast":        e.collectionsMethod("findLast", 2),
			"containsBy":      e.collectionsMethod("containsBy", 3),
			"indexBy":         e.collectionsMethod("indexBy", 2),
			"binarySearch":    e.collectionsMethod("binarySearch", 2),
			"lowerBound":      e.collectionsMethod("lowerBound", 2),
			"upperBound":      e.collectionsMethod("upperBound", 2),
			"minBy":           e.collectionsMethod("minBy", 2),
			"maxBy":           e.collectionsMethod("maxBy", 2),
			"sortBy":          e.collectionsMethod("sortBy", -1),
			"topBy":           e.collectionsMethod("topBy", 3),
			"sumBy":           e.collectionsMethod("sumBy", 2),
			"averageBy":       e.collectionsMethod("averageBy", 2),
			"topK":            e.collectionsMethod("topK", 2),
			"bottomK":         e.collectionsMethod("bottomK", 2),
			"frequencies":     e.collectionsMethod("frequencies", 1),
			"mode":            e.collectionsMethod("mode", 1),
			"difference":      e.collectionsMethod("difference", 2),
			"intersection":    e.collectionsMethod("intersection", 2),
			"differenceBy":    e.collectionsMethod("differenceBy", 3),
			"intersectionBy":  e.collectionsMethod("intersectionBy", 3),
			"zipWith":         e.collectionsMethod("zipWith", 3),
			"flatMap":         e.collectionsMethod("flatMap", 2),
			"uniqueBy":        e.collectionsMethod("uniqueBy", 2),
			"takeWhile":       e.collectionsMethod("takeWhile", 2),
			"dropWhile":       e.collectionsMethod("dropWhile", 2),
			"windowed":        e.collectionsMethod("windowed", -1),
			"unzip":           e.collectionsMethod("unzip", 1),
			"scan":            e.collectionsMethod("scan", 3),
			"enumerate":       e.collectionsMethod("enumerate", 1),
			"bfs":             e.collectionsGraphMethod("bfs", 1),
			"dfs":             e.collectionsGraphMethod("dfs", 1),
			"topologicalSort": e.collectionsGraphMethod("topologicalSort", 0),
			"shortestPath":    e.collectionsGraphMethod("shortestPath", 2),
		},
		"secrets": {
			"getEnv":            secretsGetEnv,
			"requireEnv":        secretsRequireEnv,
			"readFile":          secretsReadFile,
			"randomBytes":       e.registryBuiltin("secrets", "randomBytes"),
			"randomInt":         e.registryBuiltin("secrets", "randomInt"),
			"randomHex":         e.registryBuiltin("secrets", "randomHex"),
			"randomBase64":      e.registryBuiltin("secrets", "randomBase64"),
			"constantTimeEqual": e.registryBuiltin("secrets", "constantTimeEqual"),
		},
		"random": {
			"seed":      e.registryBuiltin("random", "seed"),
			"next":      e.registryBuiltin("random", "next"),
			"intRange":  e.registryBuiltin("random", "intRange"),
			"float":     e.registryBuiltin("random", "float"),
			"bool":      e.registryBuiltin("random", "bool"),
			"choice":    e.registryBuiltin("random", "choice"),
			"shuffle":   e.registryBuiltin("random", "shuffle"),
			"Generator": e.registryBuiltin("random", "Generator"),
		},
		"strbuilder": {
			"new":        e.registryBuiltin("strbuilder", "new"),
			"append":     e.registryBuiltin("strbuilder", "append"),
			"appendLine": e.registryBuiltin("strbuilder", "appendLine"),
			"build":      e.registryBuiltin("strbuilder", "build"),
			"length":     e.registryBuiltin("strbuilder", "length"),
			"clear":      e.registryBuiltin("strbuilder", "clear"),
			"dispose":    e.registryBuiltin("strbuilder", "dispose"),
		},
		"time": {
			"now":          e.registryBuiltin("time", "now"),
			"elapsed":      e.registryBuiltin("time", "elapsed"),
			"sleep":        e.registryBuiltin("time", "sleep"),
			"monotonic":    e.registryBuiltin("time", "monotonic"),
			"monotonicNs":  e.registryBuiltin("time", "monotonicNs"),
			"unix":         e.registryBuiltin("time", "unix"),
			"unixMilli":    e.registryBuiltin("time", "unixMilli"),
			"unixMicro":    e.registryBuiltin("time", "unixMicro"),
			"unixNano":     e.registryBuiltin("time", "unixNano"),
			"unixFloat":    e.registryBuiltin("time", "unixFloat"),
			"unixDecimal":  e.registryBuiltin("time", "unixDecimal"),
			"elapsedFloat": e.registryBuiltin("time", "elapsedFloat"),
			"humanize":     e.registryBuiltin("time", "humanize"),
		},
		"profiler": {
			"snapshot": e.registryBuiltin("profiler", "snapshot"),
			"delta":    e.registryBuiltin("profiler", "delta"),
			"memory":   e.registryBuiltin("profiler", "memory"),
			"cpu":      e.registryBuiltin("profiler", "cpu"),
			"peak":     e.registryBuiltin("profiler", "peak"),
		},
		"schema": {
			"validate": schemaValidate,
		},
		"serde": {
			"parse":     e.serdeParse,
			"stringify": e.serdeStringify,
		},
		"metrics": {
			"inc":          e.metricsInc,
			"set":          e.metricsSet,
			"get":          e.metricsGet,
			"snapshot":     e.metricsSnapshot,
			"reset":        e.metricsReset,
			"now":          metricsNow,
			"duration":     metricsDuration,
			"counter":      e.metricsCounter,
			"gauge":        e.metricsGauge,
			"histogram":    e.metricsHistogram,
			"observe":      e.metricsObserve,
			"toPrometheus": e.metricsToPrometheus,
		},
		"trace": {
			"start":      e.traceStart,
			"event":      e.traceEvent,
			"end":        e.traceEnd,
			"snapshot":   e.traceSnapshot,
			"reset":      e.traceReset,
			"toOtlpJson": e.traceToOtlpJson,
			"exportOtlp": e.traceExportOtlp,
		},
		"profile": {
			"memStats": profileMemStats,
			"gc":       profileGC,
			"now":      metricsNow,
			"elapsed":  metricsDuration,
		},
		"web": {
			"new":            e.webNew,
			"use":            e.webUse,
			"before":         e.webBefore,
			"after":          e.webUse,
			"route":          e.webRoute,
			"get":            e.webGet,
			"post":           e.webPost,
			"handle":         e.webHandle,
			"withHeader":     webWithHeader,
			"parseMultipart": webParseMultipart,
		},
		"crypt": {
			"md5":                    e.registryBuiltin("crypt", "md5"),
			"sha1":                   e.registryBuiltin("crypt", "sha1"),
			"sha256":                 e.registryBuiltin("crypt", "sha256"),
			"sha512":                 e.registryBuiltin("crypt", "sha512"),
			"sha3_256":               e.registryBuiltin("crypt", "sha3_256"),
			"blake2b":                e.registryBuiltin("crypt", "blake2b"),
			"crc32":                  e.registryBuiltin("crypt", "crc32"),
			"hmacSha256":             e.registryBuiltin("crypt", "hmacSha256"),
			"hmacSha256Bytes":        e.registryBuiltin("crypt", "hmacSha256Bytes"),
			"bcryptHash":             e.registryBuiltin("crypt", "bcryptHash"),
			"bcryptVerify":           e.registryBuiltin("crypt", "bcryptVerify"),
			"argon2idHash":           e.registryBuiltin("crypt", "argon2idHash"),
			"argon2idVerify":         e.registryBuiltin("crypt", "argon2idVerify"),
			"passwordHash":           e.registryBuiltin("crypt", "passwordHash"),
			"passwordVerify":         e.registryBuiltin("crypt", "passwordVerify"),
			"randomHex":              e.registryBuiltin("crypt", "randomHex"),
			"base64Encode":           e.registryBuiltin("crypt", "base64Encode"),
			"base64Decode":           e.registryBuiltin("crypt", "base64Decode"),
			"jwtSign":                e.registryBuiltin("crypt", "jwtSign"),
			"jwtVerify":              e.registryBuiltin("crypt", "jwtVerify"),
			"jwtDecode":              e.registryBuiltin("crypt", "jwtDecode"),
			"jwk":                    e.registryBuiltin("crypt", "jwk"),
			"jwks":                   e.registryBuiltin("crypt", "jwks"),
			"generateRsaKey":         e.registryBuiltin("crypt", "generateRsaKey"),
			"generateEcKey":          e.registryBuiltin("crypt", "generateEcKey"),
			"generateEd25519Key":     e.registryBuiltin("crypt", "generateEd25519Key"),
			"publicKey":              e.registryBuiltin("crypt", "publicKey"),
			"generateSelfSignedCert": e.registryBuiltin("crypt", "generateSelfSignedCert"),
			"generateCsr":            e.registryBuiltin("crypt", "generateCsr"),
			"parseCert":              e.registryBuiltin("crypt", "parseCert"),
			"signCertificate":        e.registryBuiltin("crypt", "signCertificate"),
			"verifyCertChain":        e.registryBuiltin("crypt", "verifyCertChain"),
			"asn1Decode":             e.registryBuiltin("crypt", "asn1Decode"),
			"parseAndroidAttestation": e.registryBuiltin("crypt", "parseAndroidAttestation"),
			"pkcs12Decode":           e.registryBuiltin("crypt", "pkcs12Decode"),
			"jweEncrypt":             e.registryBuiltin("crypt", "jweEncrypt"),
			"jweDecrypt":             e.registryBuiltin("crypt", "jweDecrypt"),
			"jwtSignRS256":           e.registryBuiltin("crypt", "jwtSignRS256"),
			"jwtVerifyRS256":         e.registryBuiltin("crypt", "jwtVerifyRS256"),
			"jwtSignES256":           e.registryBuiltin("crypt", "jwtSignES256"),
			"jwtVerifyES256":         e.registryBuiltin("crypt", "jwtVerifyES256"),
			"aesEncrypt":             e.registryBuiltin("crypt", "aesEncrypt"),
			"aesDecrypt":             e.registryBuiltin("crypt", "aesDecrypt"),
			"chacha20Encrypt":        e.registryBuiltin("crypt", "chacha20Encrypt"),
			"chacha20Decrypt":        e.registryBuiltin("crypt", "chacha20Decrypt"),
		},
		"binary": {
			"pack":        e.registryBuiltin("binary", "pack"),
			"unpack":      e.registryBuiltin("binary", "unpack"),
			"unpackNamed": e.registryBuiltin("binary", "unpackNamed"),
			"size":        e.registryBuiltin("binary", "size"),
		},
		"encoding": {
			"base64Encode":    e.registryBuiltin("encoding", "base64Encode"),
			"base64Decode":    e.registryBuiltin("encoding", "base64Decode"),
			"base32Encode":    e.registryBuiltin("encoding", "base32Encode"),
			"base32Decode":    e.registryBuiltin("encoding", "base32Decode"),
			"base58Encode":    e.registryBuiltin("encoding", "base58Encode"),
			"base58Decode":    e.registryBuiltin("encoding", "base58Decode"),
			"base64UrlEncode": e.registryBuiltin("encoding", "base64UrlEncode"),
			"base64UrlDecode": e.registryBuiltin("encoding", "base64UrlDecode"),
			"urlEncode":       e.registryBuiltin("encoding", "urlEncode"),
			"urlDecode":       e.registryBuiltin("encoding", "urlDecode"),
			"htmlEscape":      e.registryBuiltin("encoding", "htmlEscape"),
			"htmlUnescape":    e.registryBuiltin("encoding", "htmlUnescape"),
			"sanitizeHtml":    e.registryBuiltin("encoding", "sanitizeHtml"),
		},
		"compress": {
			"gzip":   e.registryBuiltin("compress", "gzip"),
			"gunzip": e.registryBuiltin("compress", "gunzip"),
		},
		"archive": {
			"zipRead":    e.registryBuiltin("archive", "zipRead"),
			"zipWrite":   e.registryBuiltin("archive", "zipWrite"),
			"tarRead":    e.registryBuiltin("archive", "tarRead"),
			"tarWrite":   e.registryBuiltin("archive", "tarWrite"),
			"tarGzRead":  e.registryBuiltin("archive", "tarGzRead"),
			"tarGzWrite": e.registryBuiltin("archive", "tarGzWrite"),
		},
		"url": {
			"URL":       e.registryBuiltin("url", "URL"),
			"parse":     e.registryBuiltin("url", "parse"),
			"stringify": e.registryBuiltin("url", "stringify"),
			"encode":    e.registryBuiltin("url", "encode"),
			"decode":    e.registryBuiltin("url", "decode"),
			"joinPath":  e.registryBuiltin("url", "joinPath"),
		},
		"template": {
			"renderString": e.registryBuiltin("template", "renderString"),
			"Template":     e.registryBuiltin("template", "Template"),
			"load":         e.registryBuiltin("template", "load"),
			"Engine":       e.registryBuiltin("template", "Engine"),
		},
		"re": {
			"test":     e.registryBuiltin("re", "test"),
			"find":     e.registryBuiltin("re", "find"),
			"findAll":  e.registryBuiltin("re", "findAll"),
			"match":    e.registryBuiltin("re", "match"),
			"matchAll": e.registryBuiltin("re", "matchAll"),
			"replace":  e.registryBuiltin("re", "replace"),
			"split":    e.registryBuiltin("re", "split"),
			"compile":  e.registryBuiltin("re", "compile"),
		},
		"pcre": {
			"test":     e.registryBuiltin("pcre", "test"),
			"find":     e.registryBuiltin("pcre", "find"),
			"findAll":  e.registryBuiltin("pcre", "findAll"),
			"match":    e.registryBuiltin("pcre", "match"),
			"matchAll": e.registryBuiltin("pcre", "matchAll"),
			"replace":  e.registryBuiltin("pcre", "replace"),
			"split":    e.registryBuiltin("pcre", "split"),
			"quote":    e.registryBuiltin("pcre", "quote"),
			"compile":  e.registryBuiltin("pcre", "compile"),
		},
		"dataframe": {
			"fromDict":    e.registryBuiltin("dataframe", "fromDict"),
			"fromRecords": e.registryBuiltin("dataframe", "fromRecords"),
			"fromCsv":     e.registryBuiltin("dataframe", "fromCsv"),
			"fromJson":    e.registryBuiltin("dataframe", "fromJson"),
			"col":         e.registryBuiltin("dataframe", "col"),
			"lit":         e.registryBuiltin("dataframe", "lit"),
			"concat":      e.registryBuiltin("dataframe", "concat"),
			"readCsv":     e.dataframeReadCsv,
			"writeCsv":    dataframeWriteCsv,
			"fromQuery":   e.dataframeFromQuery,
			"toTable":     e.dataframeToTable,
		},
		"ndarray": {
			"array":    e.registryBuiltin("ndarray", "array"),
			"zeros":    e.registryBuiltin("ndarray", "zeros"),
			"ones":     e.registryBuiltin("ndarray", "ones"),
			"full":     e.registryBuiltin("ndarray", "full"),
			"eye":      e.registryBuiltin("ndarray", "eye"),
			"arange":   e.registryBuiltin("ndarray", "arange"),
			"linspace": e.registryBuiltin("ndarray", "linspace"),
			"random":   e.registryBuiltin("ndarray", "random"),
			"randn":    e.registryBuiltin("ndarray", "randn"),
			"solve":    e.registryBuiltin("ndarray", "solve"),
			"inv":      e.registryBuiltin("ndarray", "inv"),
			"det":      e.registryBuiltin("ndarray", "det"),
		},
		"stats": {
			"normal":      e.registryBuiltin("stats", "normal"),
			"uniform":     e.registryBuiltin("stats", "uniform"),
			"exponential": e.registryBuiltin("stats", "exponential"),
			"lognormal":   e.registryBuiltin("stats", "lognormal"),
			"weibull":     e.registryBuiltin("stats", "weibull"),
			"gamma":       e.registryBuiltin("stats", "gamma"),
			"chiSquared":  e.registryBuiltin("stats", "chiSquared"),
			"beta":        e.registryBuiltin("stats", "beta"),
			"studentT":    e.registryBuiltin("stats", "studentT"),
			"f":           e.registryBuiltin("stats", "f"),
			"binomial":         e.registryBuiltin("stats", "binomial"),
			"poisson":          e.registryBuiltin("stats", "poisson"),
			"tTestOneSample":        e.registryBuiltin("stats", "tTestOneSample"),
			"tTestIndependent":      e.registryBuiltin("stats", "tTestIndependent"),
			"tTestPaired":           e.registryBuiltin("stats", "tTestPaired"),
			"chiSquareTest":         e.registryBuiltin("stats", "chiSquareTest"),
			"chiSquareIndependence": e.registryBuiltin("stats", "chiSquareIndependence"),
			"mannWhitneyU":          e.registryBuiltin("stats", "mannWhitneyU"),
			"ksTest":                e.registryBuiltin("stats", "ksTest"),
			"confidenceIntervalMean":       e.registryBuiltin("stats", "confidenceIntervalMean"),
			"confidenceIntervalProportion": e.registryBuiltin("stats", "confidenceIntervalProportion"),
			"confidenceIntervalDiffMeans":  e.registryBuiltin("stats", "confidenceIntervalDiffMeans"),
			"linregress":                   e.registryBuiltin("stats", "linregress"),
			"polyfit":                      e.registryBuiltin("stats", "polyfit"),
			"polyval":                      e.registryBuiltin("stats", "polyval"),
			"skewness":                     e.registryBuiltin("stats", "skewness"),
			"kurtosis":                     e.registryBuiltin("stats", "kurtosis"),
			"covariance":                   e.registryBuiltin("stats", "covariance"),
			"corrcoef":                     e.registryBuiltin("stats", "corrcoef"),
		},
		"complex": {
			"of":        e.registryBuiltin("complex", "of"),
			"fromPolar": e.registryBuiltin("complex", "fromPolar"),
		},
		"physics": {
			"c":                e.registryBuiltin("physics", "c"),
			"G":                e.registryBuiltin("physics", "G"),
			"planck":           e.registryBuiltin("physics", "planck"),
			"hbar":             e.registryBuiltin("physics", "hbar"),
			"avogadro":         e.registryBuiltin("physics", "avogadro"),
			"boltzmann":        e.registryBuiltin("physics", "boltzmann"),
			"gasConstant":      e.registryBuiltin("physics", "gasConstant"),
			"elementaryCharge": e.registryBuiltin("physics", "elementaryCharge"),
			"electronMass":     e.registryBuiltin("physics", "electronMass"),
			"protonMass":       e.registryBuiltin("physics", "protonMass"),
			"stefanBoltzmann":  e.registryBuiltin("physics", "stefanBoltzmann"),
			"gravity":          e.registryBuiltin("physics", "gravity"),
			"convert":          e.registryBuiltin("physics", "convert"),
		},
		"geo": {
			"haversineDistance": e.registryBuiltin("geo", "haversineDistance"),
			"bearing":           e.registryBuiltin("geo", "bearing"),
			"midpoint":          e.registryBuiltin("geo", "midpoint"),
			"destination":       e.registryBuiltin("geo", "destination"),
		},
		"markdown": {
			"parse":      e.registryBuiltin("markdown", "parse"),
			"renderHtml": e.registryBuiltin("markdown", "renderHtml"),
			"stripText":  e.registryBuiltin("markdown", "stripText"),
		},
		"datetime": {
			"nowUnix":       e.registryBuiltin("datetime", "nowUnix"),
			"unix":          e.registryBuiltin("datetime", "unix"),
			"parse":         e.registryBuiltin("datetime", "parse"),
			"format":        e.registryBuiltin("datetime", "format"),
			"addSeconds":    e.registryBuiltin("datetime", "addSeconds"),
			"addDays":       e.registryBuiltin("datetime", "addDays"),
			"addMonths":     e.registryBuiltin("datetime", "addMonths"),
			"addYears":      e.registryBuiltin("datetime", "addYears"),
			"diff":          e.registryBuiltin("datetime", "diff"),
			"toLocal":       e.registryBuiltin("datetime", "toLocal"),
			"toUtc":         e.registryBuiltin("datetime", "toUtc"),
			"now":           e.registryBuiltin("datetime", "now"),
			"nowInstant":    e.registryBuiltin("datetime", "nowInstant"),
			"Instant":       e.registryBuiltin("datetime", "Instant"),
			"Duration":      e.registryBuiltin("datetime", "Duration"),
			"Zone":          e.registryBuiltin("datetime", "Zone"),
			"sleep":         sysSleep,
			"make":          e.registryBuiltin("datetime", "make"),
			"formatRFC3339": e.registryBuiltin("datetime", "formatRFC3339"),
			"formatDate":    e.registryBuiltin("datetime", "formatDate"),
			"formatTime":    e.registryBuiltin("datetime", "formatTime"),
			"formatHTTP":    e.registryBuiltin("datetime", "formatHTTP"),
			"parseRFC3339":  e.registryBuiltin("datetime", "parseRFC3339"),
			"partsInZone":   e.registryBuiltin("datetime", "partsInZone"),
			"weekdayName":   e.registryBuiltin("datetime", "weekdayName"),
			"monthName":     e.registryBuiltin("datetime", "monthName"),
		},
		"uuid": {
			"v1":            e.registryBuiltin("uuid", "v1"),
			"v4":            e.registryBuiltin("uuid", "v4"),
			"v7":            e.registryBuiltin("uuid", "v7"),
			"v3":            e.registryBuiltin("uuid", "v3"),
			"v5":            e.registryBuiltin("uuid", "v5"),
			"parse":         e.registryBuiltin("uuid", "parse"),
			"isValid":       e.registryBuiltin("uuid", "isValid"),
			"nil":           e.registryBuiltin("uuid", "nil"),
			"toBytes":       e.registryBuiltin("uuid", "toBytes"),
			"fromBytes":     e.registryBuiltin("uuid", "fromBytes"),
			"namespaceDNS":  e.registryBuiltin("uuid", "namespaceDNS"),
			"namespaceURL":  e.registryBuiltin("uuid", "namespaceURL"),
			"namespaceOID":  e.registryBuiltin("uuid", "namespaceOID"),
			"namespaceX500": e.registryBuiltin("uuid", "namespaceX500"),
			"ulid":          e.registryBuiltin("uuid", "ulid"),
		},
		"args": {
			"parse": e.registryBuiltin("args", "parse"),
			"help":  e.registryBuiltin("args", "help"),
		},
		"dotenv": {
			"parse":        e.dotenvParse,
			"load":         e.dotenvLoad,
			"apply":        e.dotenvApply,
			"loadAndApply": e.dotenvLoadAndApply,
		},
		"cli": {
			"prompt":         e.cliPrompt,
			"password":       e.cliPassword,
			"secret":         e.cliPassword,
			"confirm":        e.cliConfirm,
			"choose":         e.cliChoose,
			"multiChoose":    e.cliMultiChoose,
			"style":          cliStyle,
			"stripAnsi":      cliStripANSI,
			"table":          cliTable,
			"parseArgs":      e.registryBuiltin("args", "parse"),
			"help":           e.registryBuiltin("args", "help"),
			"spinnerTick":    e.cliSpinnerTick,
			"spinnerStop":    e.cliSpinnerStop,
			"progressRender": e.cliProgressRender,
			"progressFinish": e.cliProgressFinish,
		},
		"http": {
			"serve":              e.httpServe,
			"listen":             e.httpListen,
			"close":              e.httpClose,
			"shutdown":           e.httpShutdown,
			"wait":               e.httpWait,
			"serverAddr":         e.httpServerAddr,
			"serverCert":         e.httpServerCert,
			"serverStats":        e.httpServerStats,
			"stream":             httpStreamResponse,
			"streamWrite":        e.httpStreamWrite,
			"streamFlush":        e.httpStreamFlush,
			"streamClose":        e.httpStreamClose,
			"get":                httpGet,
			"post":               e.httpPost,
			"postJson":           httpPostJSON,
			"parseJson":          httpParseJSON,
			"request":            e.httpRequest,
			"requestWithOptions": e.httpRequestWithOptions,
			"requestStream":      e.httpRequestStream,
			"Headers":            httpHeadersObject,
			"Cookie":             httpCookieObject,
			"response":           e.httpResponseObject,
			"jsonResponse":       e.httpJSONResponseObject,
			"redirect":           e.httpRedirectObject,
			"newClient":          e.httpNewClient,
			"newCookieJar":       e.httpNewCookieJar,
			"build":              e.httpBuild,
			"fetchAll":           e.httpFetchAll,
			"getAll":             e.httpGetAll,
			"fetchStream":        e.httpFetchStream,
		},
		"websocket": {
			"connect":   e.websocketConnect,
			"upgrade":   websocketUpgradeResponse,
			"sendText":  e.websocketSendText,
			"readText":  e.websocketReadText,
			"sendBytes": e.websocketSendBytes,
			"readBytes": e.websocketReadBytes,
			"close":     e.websocketClose,
		},
		"smtp": {
			"message": smtpMessageBuiltin,
			"send":    smtpSendBuiltin,
		},
		"db": {
			"Connection": e.dbConnectionObject,
			"connect":    e.dbConnectionObject,
			"open":       e.dbOpen,
			"exec":       e.dbExec,
			"query":      e.dbQuery,
			"begin":      e.dbBegin,
			"txExec":     e.dbTxExec,
			"txQuery":    e.dbTxQuery,
			"commit":     e.dbCommit,
			"rollback":   e.dbRollback,
			"prepare":    e.dbPrepare,
			"stmtExec":   e.dbStmtExec,
			"stmtQuery":  e.dbStmtQuery,
			"stmtClose":  e.dbStmtClose,
			"configure":  e.dbConfigure,
			"stats":      e.dbStats,
			"optimize":   e.dbOptimize,
			"migrate":    e.dbMigrate,
			"close":      e.dbClose,
		},
		"ext":       e.extBuiltins(),
		"ffinative": e.ffiBuiltins(),
		"net": {
			"joinHostPort":  netJoinHostPort,
			"splitHostPort": netSplitHostPort,
			"lookupHost":    netLookupHost,
			"parseIp":       netParseIP,
			"parseCidr":     netParseCIDR,
			"cidrContains":  netCIDRContains,
			"cidrRange":     netCIDRRange,
			"isIpv4":        netIsIPv4,
			"isIpv6":        netIsIPv6,
			"ipToBytes":     netIPToBytes,
			"ipFromBytes":   netIPFromBytes,
			"listenTcp":     e.netListenTCP,
			"connectTcp":    e.netConnectTCP,
			"accept":        e.netAccept,
			"read":          e.netRead,
			"write":         e.netWrite,
			"setDeadline":   e.netSetDeadline,
			"clearDeadline": e.netClearDeadline,
			"close":         e.netClose,
			"localAddr":     e.netLocalAddr,
			"remoteAddr":    e.netRemoteAddr,
			"listenUdp":     e.netListenUDP,
			"dialUdp":       e.netDialUDP,
			"readFrom":      e.netReadFrom,
			"writeTo":       e.netWriteTo,
			"dial":          e.netDial,
			"serve":         e.netServe,
			"closeListener": e.netCloseListener,
			"serverStats":   e.netServerStats,
		},
		"test": {
			"run":        e.testRun,
			"mock":       e.testMock,
			"restore":    e.testRestore,
			"restoreAll": e.testRestoreAll,
		},
		"reflect": {
			"decorators":       reflectDecorators,
			"hasDecorator":     reflectHasDecorator,
			"decorator":        reflectDecorator,
			"parameters":       reflectParameters,
			"returnType":       reflectReturnType,
			"doc":              reflectDoc,
			"docs":             reflectDocs,
			"typeOf":           reflectTypeOf,
			"location":         reflectLocation,
			"exports":          reflectExports,
			"fields":           reflectFields,
			"getField":         reflectGetField,
			"setField":         reflectSetField,
			"methods":          reflectMethods,
			"staticMethods":    reflectStaticMethods,
			"parent":           reflectParent,
			"className":        reflectClassName,
			"interfaces":       reflectInterfaces,
			"constructors":     reflectConstructors,
			"typeBindings":     reflectTypeBindings,
			"interfaceMethods": reflectInterfaceMethods,
			"interfaceParents": reflectInterfaceParents,
			"function":         reflectLookupRequiresEvaluator,
			"class":            reflectLookupRequiresEvaluator,
			"module":           reflectLookupRequiresEvaluator,
			"method":           e.reflectMethodBound,
			"staticMethod":     reflectStaticMethod,
		},
		"log": {
			"stdout":   e.logStdout,
			"stderr":   e.logStderr,
			"file":     e.logFile,
			"toStream": e.logToStream,
			"custom":   e.logCustom,
			"info":     e.logInfo,
			"warn":     e.logWarn,
			"error":    e.logError,
			"debug":    e.logDebug,
			"close":    e.logClose,
		},
		"path": {
			"join":  pathJoin,
			"clean": pathClean,
			"base":  pathBase,
			"dir":   pathDir,
			"ext":   pathExt,
			"abs":   pathAbs,
			"rel":   pathRel,
			"glob":  pathGlob,
		},
		"watch": {
			"snapshot": watchSnapshot,
			"wait":     watchWait,
			"start":    e.watchStart,
			"stop":     e.watchStop,
		},
		"math": {
			"abs":        e.registryBuiltin("math", "abs"),
			"min":        e.registryBuiltin("math", "min"),
			"max":        e.registryBuiltin("math", "max"),
			"clamp":      e.registryBuiltin("math", "clamp"),
			"floor":      e.registryBuiltin("math", "floor"),
			"ceil":       e.registryBuiltin("math", "ceil"),
			"lerp":       e.registryBuiltin("math", "lerp"),
			"remap":      e.registryBuiltin("math", "remap"),
			"round":      e.registryBuiltin("math", "round"),
			"sqrt":       e.registryBuiltin("math", "sqrt"),
			"sin":        e.registryBuiltin("math", "sin"),
			"cos":        e.registryBuiltin("math", "cos"),
			"tan":        e.registryBuiltin("math", "tan"),
			"asin":       e.registryBuiltin("math", "asin"),
			"acos":       e.registryBuiltin("math", "acos"),
			"atan":       e.registryBuiltin("math", "atan"),
			"atan2":      e.registryBuiltin("math", "atan2"),
			"log":        e.registryBuiltin("math", "log"),
			"log10":      e.registryBuiltin("math", "log10"),
			"exp":        e.registryBuiltin("math", "exp"),
			"pow":        e.registryBuiltin("math", "pow"),
			"pi":         e.registryBuiltin("math", "pi"),
			"e":          e.registryBuiltin("math", "e"),
			"log2":       e.registryBuiltin("math", "log2"),
			"trunc":      e.registryBuiltin("math", "trunc"),
			"sign":       e.registryBuiltin("math", "sign"),
			"cbrt":       e.registryBuiltin("math", "cbrt"),
			"hypot":      e.registryBuiltin("math", "hypot"),
			"inf":        e.registryBuiltin("math", "inf"),
			"nan":        e.registryBuiltin("math", "nan"),
			"isNaN":      e.registryBuiltin("math", "isNaN"),
			"isInf":      e.registryBuiltin("math", "isInf"),
			"isPrime":    e.registryBuiltin("math", "isPrime"),
			"median":     e.registryBuiltin("math", "median"),
			"percentile": e.registryBuiltin("math", "percentile"),
			"quantile":   e.registryBuiltin("math", "quantile"),
			"mode":       e.registryBuiltin("math", "mode"),
			"tau":        e.registryBuiltin("math", "tau"),
			"ln2":        e.registryBuiltin("math", "ln2"),
			"ln10":       e.registryBuiltin("math", "ln10"),
			"sqrt2":      e.registryBuiltin("math", "sqrt2"),
			"phi":        e.registryBuiltin("math", "phi"),
			"maxInt":     e.registryBuiltin("math", "maxInt"),
			"minInt":     e.registryBuiltin("math", "minInt"),
			"maxFloat":   e.registryBuiltin("math", "maxFloat"),
			"minFloat":   e.registryBuiltin("math", "minFloat"),
			"epsilon":    e.registryBuiltin("math", "epsilon"),
			"sqrt2Pi":    e.registryBuiltin("math", "sqrt2Pi"),
			"log2Pi":     e.registryBuiltin("math", "log2Pi"),
			"gamma":      e.registryBuiltin("math", "gamma"),
			"lgamma":     e.registryBuiltin("math", "lgamma"),
			"beta":       e.registryBuiltin("math", "beta"),
			"lbeta":      e.registryBuiltin("math", "lbeta"),
			"erf":        e.registryBuiltin("math", "erf"),
			"erfc":       e.registryBuiltin("math", "erfc"),
			"erfinv":     e.registryBuiltin("math", "erfinv"),
			"j0":         e.registryBuiltin("math", "j0"),
			"j1":         e.registryBuiltin("math", "j1"),
			"jn":         e.registryBuiltin("math", "jn"),
			"y0":         e.registryBuiltin("math", "y0"),
			"y1":         e.registryBuiltin("math", "y1"),
			"yn":         e.registryBuiltin("math", "yn"),
			"factorial":  e.registryBuiltin("math", "factorial"),
			"comb":       e.registryBuiltin("math", "comb"),
			"perm":       e.registryBuiltin("math", "perm"),
			"gcd":        e.registryBuiltin("math", "gcd"),
			"lcm":        e.registryBuiltin("math", "lcm"),
			"lcomb":      e.registryBuiltin("math", "lcomb"),
		},
		"vecmath": {
			"score":          e.registryBuiltin("vecmath", "score"),
			"topK":           e.registryBuiltin("vecmath", "topK"),
			"normalize":      e.registryBuiltin("vecmath", "normalize"),
			"semanticSearch": e.registryBuiltin("vecmath", "semanticSearch"),
		},
		"transformers": {
			"tokenize": e.registryBuiltin("transformers", "tokenize"),
			"pool":     e.registryBuiltin("transformers", "pool"),
		},
		"onnx": {
			"session": e.onnxSession,
		},
		"browser": {
			"launch": e.browserLaunch,
		},
		"hnsw": {
			"new":    e.registryBuiltin("hnsw", "new"),
			"add":    e.registryBuiltin("hnsw", "add"),
			"get":    e.registryBuiltin("hnsw", "get"),
			"delete": e.registryBuiltin("hnsw", "delete"),
			"count":  e.registryBuiltin("hnsw", "count"),
			"clear":  e.registryBuiltin("hnsw", "clear"),
			"search": e.registryBuiltin("hnsw", "search"),
		},
		"secureRandom": {
			"openSession":      e.registryBuiltin("secureRandom", "openSession"),
			"fromSeed":         e.registryBuiltin("secureRandom", "fromSeed"),
			"commitment":       e.registryBuiltin("secureRandom", "commitment"),
			"reveal":           e.registryBuiltin("secureRandom", "reveal"),
			"auditLog":         e.registryBuiltin("secureRandom", "auditLog"),
			"auditLogJson":     e.registryBuiltin("secureRandom", "auditLogJson"),
			"bytes":            e.registryBuiltin("secureRandom", "bytes"),
			"uintRange":        e.registryBuiltin("secureRandom", "uintRange"),
			"float":            e.registryBuiltin("secureRandom", "float"),
			"bool":             e.registryBuiltin("secureRandom", "bool"),
			"choice":           e.registryBuiltin("secureRandom", "choice"),
			"shuffle":          e.registryBuiltin("secureRandom", "shuffle"),
			"weightedChoice":   e.registryBuiltin("secureRandom", "weightedChoice"),
			"verifyCommitment": e.registryBuiltin("secureRandom", "verifyCommitment"),
			"replay":           e.registryBuiltin("secureRandom", "replay"),
		},
		"msgpack": {
			"encode":    e.registryBuiltin("msgpack", "encode"),
			"decode":    e.registryBuiltin("msgpack", "decode"),
			"tryDecode": e.registryBuiltin("msgpack", "tryDecode"),
			"validate":  e.registryBuiltin("msgpack", "validate"),
		},
		"unicode": {
			"normalize":    e.registryBuiltin("unicode", "normalize"),
			"isNormalized": e.registryBuiltin("unicode", "isNormalized"),
		},
		"cron": {
			"parse":     e.registryBuiltin("cron", "parse"),
			"isValid":   e.registryBuiltin("cron", "isValid"),
			"nextAfter": e.registryBuiltin("cron", "nextAfter"),
			"nextN":     e.registryBuiltin("cron", "nextN"),
		},
		"async.sync": {
			"mutexNew":            e.registryBuiltin("async.sync", "mutexNew"),
			"mutexLock":           e.registryBuiltin("async.sync", "mutexLock"),
			"mutexUnlock":         e.registryBuiltin("async.sync", "mutexUnlock"),
			"mutexTryLock":        e.registryBuiltin("async.sync", "mutexTryLock"),
			"rwmutexNew":          e.registryBuiltin("async.sync", "rwmutexNew"),
			"rwmutexLock":         e.registryBuiltin("async.sync", "rwmutexLock"),
			"rwmutexUnlock":       e.registryBuiltin("async.sync", "rwmutexUnlock"),
			"rwmutexTryLock":      e.registryBuiltin("async.sync", "rwmutexTryLock"),
			"rwmutexRLock":        e.registryBuiltin("async.sync", "rwmutexRLock"),
			"rwmutexRUnlock":      e.registryBuiltin("async.sync", "rwmutexRUnlock"),
			"rwmutexTryRLock":     e.registryBuiltin("async.sync", "rwmutexTryRLock"),
			"semaphoreNew":        e.registryBuiltin("async.sync", "semaphoreNew"),
			"semaphoreAcquire":    e.registryBuiltin("async.sync", "semaphoreAcquire"),
			"semaphoreRelease":    e.registryBuiltin("async.sync", "semaphoreRelease"),
			"semaphoreTryAcquire": e.registryBuiltin("async.sync", "semaphoreTryAcquire"),
			"waitgroupNew":        e.registryBuiltin("async.sync", "waitgroupNew"),
			"waitgroupAdd":        e.registryBuiltin("async.sync", "waitgroupAdd"),
			"waitgroupDone":       e.registryBuiltin("async.sync", "waitgroupDone"),
			"waitgroupWait":       e.registryBuiltin("async.sync", "waitgroupWait"),
		},
		"async.atomic": {
			"intNew":             e.registryBuiltin("async.atomic", "intNew"),
			"intLoad":            e.registryBuiltin("async.atomic", "intLoad"),
			"intStore":           e.registryBuiltin("async.atomic", "intStore"),
			"intAdd":             e.registryBuiltin("async.atomic", "intAdd"),
			"intCompareAndSwap":  e.registryBuiltin("async.atomic", "intCompareAndSwap"),
			"boolNew":            e.registryBuiltin("async.atomic", "boolNew"),
			"boolLoad":           e.registryBuiltin("async.atomic", "boolLoad"),
			"boolStore":          e.registryBuiltin("async.atomic", "boolStore"),
			"boolCompareAndSwap": e.registryBuiltin("async.atomic", "boolCompareAndSwap"),
		},
		"async.channel": {
			"make":     e.registryBuiltin("async.channel", "make"),
			"send":     e.registryBuiltin("async.channel", "send"),
			"recv":     e.registryBuiltin("async.channel", "recv"),
			"tryRecv":  e.registryBuiltin("async.channel", "tryRecv"),
			"trySend":  e.registryBuiltin("async.channel", "trySend"),
			"close":    e.registryBuiltin("async.channel", "close"),
			"isClosed": e.registryBuiltin("async.channel", "isClosed"),
		},
		"store": {
			"new":           e.registryBuiltin("store", "new"),
			"set":           e.registryBuiltin("store", "set"),
			"get":           e.registryBuiltin("store", "get"),
			"has":           e.registryBuiltin("store", "has"),
			"delete":        e.registryBuiltin("store", "delete"),
			"clear":         e.registryBuiltin("store", "clear"),
			"len":           e.registryBuiltin("store", "len"),
			"keys":          e.registryBuiltin("store", "keys"),
			"values":        e.registryBuiltin("store", "values"),
			"incr":          e.registryBuiltin("store", "incr"),
			"getOrSet":      e.registryBuiltin("store", "getOrSet"),
			"compareAndSet": e.registryBuiltin("store", "compareAndSet"),
		},
		"imagenative": {
			"blank":  e.registryBuiltin("imagenative", "blank"),
			"decode": e.registryBuiltin("imagenative", "decode"),
			"width":  e.registryBuiltin("imagenative", "width"),
			"height": e.registryBuiltin("imagenative", "height"),
			"resize": e.registryBuiltin("imagenative", "resize"),
			"crop":   e.registryBuiltin("imagenative", "crop"),
			"rotate": e.registryBuiltin("imagenative", "rotate"),
			"encode": e.registryBuiltin("imagenative", "encode"),
			"close":  e.registryBuiltin("imagenative", "close"),
		},
		"errors": {
			"new":           e.registryBuiltin("errors", "new"),
			"message":       e.registryBuiltin("errors", "message"),
			"class":         e.registryBuiltin("errors", "class"),
			"stackTrace":    e.registryBuiltin("errors", "stackTrace"),
			"frames":        e.registryBuiltin("errors", "frames"),
			"hasStackTrace": e.registryBuiltin("errors", "hasStackTrace"),
			"is": func(_ *ast.CallExpression, args []runtime.Value) (runtime.Value, error) {
				if len(args) != 2 {
					return nil, fmt.Errorf("errors.is expects two arguments")
				}
				err, ok := args[0].(runtime.Error)
				if !ok {
					return nil, fmt.Errorf("errors.is: first argument must be an error, got %s", args[0].TypeName())
				}
				target, ok := args[1].(runtime.String)
				if !ok {
					return nil, fmt.Errorf("errors.is: second argument must be a string class name")
				}
				return runtime.Bool{Value: e.errorTypeMatches(err.Class, target.Value)}, nil
			},
			"wrap": e.registryBuiltin("errors", "wrap"),
		},
		"freeze": {
			"shallow":  e.registryBuiltin("freeze", "shallow"),
			"deep":     e.registryBuiltin("freeze", "deep"),
			"isFrozen": e.registryBuiltin("freeze", "isFrozen"),
		},
		"clone": {
			"deep": e.registryBuiltin("clone", "deep"),
		},
	}
}
